[package]
name = "kaigan"
version = "0.2.1"
description = "Rust companion for Kinobi"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/kaigan"
license = "MIT"
edition = "2021"
readme = "README.md"

[dependencies]
borsh = "^0.10"
